export const Constants = {
  SET_UPLOAD_URL: 'SET_UPLOAD_URL',
  SET_PDF_FILE: 'SET_PDF_FILE',
  SET_PDF_NAME: 'SET_PDF_NAME',
  SET_PAGES: 'SET_PAGES',
  SET_PAGES_SCALE: 'SET_PAGES_SCALE',
  SET_ALL_OBJECTS: 'SET_ALL_OBJECTS',
  SET_CURRENT_FONT: 'SET_CURRENT_FONT',
  SET_SELECTED_PAGEINDEX: 'SET_SELECTED_PAGEINDEX',
  SET_SAVING: 'SET_SAVING',
  SET_ADDING_DRAWING: 'SET_ADDING_DRAWING',
  CLEAR: 'CLEAR'
};


export const StateConstants = {
  SET_UPLOAD_URL: 'upload_url',
  SET_PDF_FILE: 'pdfFile',
  SET_PDF_NAME: 'pdfName',
  SET_PAGES: 'pages',
  SET_PAGES_SCALE: 'pagesScale',
  SET_ALL_OBJECTS: 'allObjects',
  SET_CURRENT_FONT: 'currentFont',
  SET_SELECTED_PAGEINDEX: 'selectedPageIndex',
  SET_SAVING: 'saving',
  SET_ADDING_DRAWING: 'addDrawing',
}